highlighter: rouge
permalink: ./:title
title: "Toolkit"
description: "// Hopefully helpful"
author: "Mat"
url: https://tools.thechels.uk
copyright: "MB"
encoding: UTF-8
future: false
repository: Mat-0/Tools
defaultImagePath: "/images/splashscreens/apple-touch-icon-180x180.png"
github:
  repository_url: https://github.com/Mat-0/Tools
  branch: main
sass:
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-avatar
  - jekyll-github-metadata
exclude:
  - CNAME
  - README.md
  - LICENSE.md
  - SECURITY.md
  - requirements.txt
  - _python/
  - .github/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
include:
  - ".well-known"
  - "_pages"

# Site Navigation
## Header
navigation_header:
  - link: "https://thechels.uk/"
    name: "thechelsuk"
  - link: "https://cod.thechels.uk/"
    name: "Cheltenham Open Data"
  - link: "https://feeds.thechels.uk/"
    name: "News Feeds"
  - link: "https://hiyd.uk"
    name: "Hiyd"
  - link: "https://apps.apple.com/gb/developer/mat-benfield/id1818791310"
    name: "AppStore"
